const universities = [
'Massachusetts Institute of Technology (MIT) ',
'University of Oxford ',
'Stanford University ',
'University of Cambridge ',
'Harvard University ',
'California Institute of Technology (Caltech) ',
'Imperial College London  ',
'King`s College London',
'Seoul National University ',
'University of Melbourne ',
'University of Sydney ',
'Chinese University of Hong Kong (CUHK) ',
'University of California, Los Angeles (UCLA) ',
'KAIST - Korea Advanced Institute of Science & Technology ',
'New York University (NYU) ',
'University of New South Wales (UNSW Sydney) ',
'Universite PSL ',
'Zhejiang University ',
'University of British Columbia ',
'University of Queensland ',
'University of California, San Diego (UCSD) ',
'London School of Economics and Political Science (LSE) ',
'Shanghai Jiao Tong University ',
'Technical University of Munich ',
'Duke University ',
'Carnegie Mellon University ',
'City University of Hong Kong ',
'University of Amsterdam ',
'Tokyo Institute of Technology ',
'Delft University of Technology ',
'Monash University ',
'Institut Polytechnique de Paris ',
'Brown University ',
'University of Warwick ',
'University of Bristol ',
'Ruprecht-Karls-Universitat Heidelberg ',
'Ludwig-Maximilians-Universität München ',
'Universiti Malaya (UM) ',
'Hong Kong Polytechnic University ',
'National Taiwan University (NTU) ',
'Universidad de Buenos Aires (UBA) ',
'KU Leuven ',
'University of Zurich ',
'Sorbonne University ',
'University of Glasgow ',
'Korea University ',
'Osaka University ',
'University of Wisconsin-Madison ',
'University of Southampton ',
'Lomonosov Moscow State University ',
'University of Copenhagen ',
'Yonsei University ',
'Pohang University of Science and Technology (POSTECH) ',
'Durham University ',
'Tohoku University ',
'University of Illinois at Urbana-Champaign ',
'University of Auckland ',
'University of Washington ',
'Lund University ',
'KTH Royal Institute of Technology ',
'University of Birmingham ',
'University of St Andrews ',
'University of Leeds ',
'University of Western Australia ',
'United States ',
'University of Sheffield ',
'University of Pennsylvania ',
'Sungkyunkwan University (SKKU) ',
'University of Science and Technology of China ',
'Technical University of Denmark ',
'University of North Carolina, Chapel Hill ',
]

module.exports = [
    universities
]