const works = [
'Accessory designer',
'Advertising designer',
'Animator',
'Architect',
'Art administrator',
'Artisan',
'Arts administration',
'Art therapist',
'Baker',
'Ceramics artist',
'Chief creative officer',
'Colorist',
'Concept Artist',
'Curator',
'Dancer',
'Design director',
'Design strategist',
'Essayist',
'Event planner',
'Fashion designer',
'Fine artist',
'Floral designer',
'Graphic designer',
'Hairstylist',
'Illustrator',
'Tattoo artist',
'Interior designer',
'Jewellery designer',
'Lyricist',
'Make-up artist',
'Marine designer',
'Media designer',
'Musician',
'Party planner',
'Penciller',
'Photographer',
'Photojournalist',
'Potter',
'Production designer',
'Sculptor',
'Set decorator',
'Set dresser',
'Singer',
'Web designer',
'Wedding planner',
'Writer',
'Anesthesiologist',
'Anesthesiology Fellow',
'Certified Registered Nurse Anesthetist',
'Registered Respiratory Therapist',
'Anesthesiologist Assistant',
'Cardiologist',
'Cardiology Fellow',
'Cardiology Physician Assistant',
'Cardiac Scientist',
'Cardiovascular Technologist',
'Urologist',
'Urology Physician Assistant',
'General Doctor',
'Bariatric Surgeon',
'Cardiothoracic surgeon',
'Cardiac Surgeon',
'Hepatic Biliary Pancreatic Surgeon',
'Neurosurgeon',
'Podiatric Surgeon',
'Surgery Physician Assistant',
'Obstetrician',
'Gynaecologist',
'OB/GYN Physician Assistant',
'Women`s Health Nurse Practitioner',
'Nurse-Midwife',
'Midwife',
'Lactation consultant',
'Radiologist',
'Radiology Physician Assistant',
'Radiotherapist',
'Radiographer',
'Orthopedic Physician',
'Orthopedic Physician Assistant',
'Sport Psychologist',
'Physical Therapist',
'Occupational Therapist',
'Physical Therapy Assistant',
'Occupational Therapy Assistant',
'Orthopaedic Technologist or Prosthetist & Orthotist',
'Chiropractor',
'Biokineticist',
'Athletic Trainer',
'Yoga Instructor',
'Massage Therapist',
'Medical Officer of Health',
'Environmental Health Officer',
'Epidemiologist',
'Public Health Nurse',
'Psychiatrist',
'Psychiatry Physician Assistant',
'Psychologist',
'Psychiatric Nurse Practitioner',
'Mental Health Nurse Practitioner',
'Occupational Therapist',
'Social Worker',
'Mental Health Counselor',
'Podiatric Surgeon',
'Doctor of Podiatric Medicine',
'Podiatrist',
'Chiropodist',
'Pharmacist',
'Pharmacy technician',
'Neonatologist',
'Pediatrician',
'Pediatric Physician Assistant',
'Neonatal Nurse Practitioner',
'Pediatric Nurse Practitioner',
'Occupational Therapist- Neonatal/ Pediatric',
'Pediatric Nurse',
'Pediatric Respiratory Therapist',
'General practitioner',
'Primary care physician',
'Internist',
'Physician assistant',
'Family nurse practitioner',
'Pharmacist',
'Pulmonologist',
'Pulmonology/Respirology Physician Assistant',
'Registered Respiratory Therapist',
'Ophthalmologist',
'Ophthalmology Physician Assistant',
'Optometrist',
'Occupational Therapist- Low Vision Rehab',
'Oncologist',
'Oncology Physician Assistant',
'Radiation Therapist',
'Arts Administrator',
'Ballet dancer',
'Corps de ballet',
'Demi-soloist',
'Principal dancer',
'Soloist',
'Ballet historian',
'Ballet master',
'Choreographer',
'Dance critic',
'Dance historian',
'Dance notator',
'Dance scholar',
'Dance therapist',
'Dancer',
'Backup dancer',
'Caller (dancing)',
'Exotic dancer',
'Majorette (dancer)',
'Showgirl',
'Taxi dancer',
'Répétiteur',
'Acrobat',
'Actor',
'Archimime',
'Athlete',
'Barker',
'Beatboxer',
'Benshi',
'Bouffon',
'Circus performer',
'Clown',
'Comedian',
'Dancer',
'Drag queen',
'Drag king',
'Emcee',
'Filmmaker',
'Flag throwing',
'Flair bartender',
'Flatulist',
'Geisha',
'Go-go dancer',
'Harlequin',
'Host',
'Illusionist',
'Impressionist',
'Internet celebrity',
'Itinerant poet',
'Kobzar',
'Lirnyk',
'Magician',
'Master of ceremonies',
'Mime',
'Minstrel',
'Monologist',
'Musician',
'Painter',
'Party princess',
'Performer',
'Photographer',
'Podcaster',
'Poet',
'Pornographic actor',
'Promotional model',
'Radio personality',
'Rapper',
'Rhapsode',
'Ring girl',
'Ringmaster',
'Scop',
'Shamakhi dancers',
'Showgirl',
'Showman',
'Showrunner',
'Singer',
'Skomorokh',
'Streamer',
'Street performer',
'Stunt performer',
'Theatre practitioner',
'TikToker',
'TV celebrity',
'Vedette',
'Writer',
'YouTuber',
'Producer',
'Director',
'Playwright',
'Dramaturge',
'Scenic designer',
'Scenographer',
'Lighting designer',
'Costume designer',
'Set designer',
'Sound designer',
'Composer',
'Music director',
'Choreographer',
'Movement person',
'Author',
'Blogger',
'Book coach',
'Commissioning editor',
'Copy editor',
'Creative consultant',
'Dog writer',
'Freelancer',
'Ghostwriter',
'Griot',
'Hack writer',
'Infopreneur',
'Journalist',
'Literary editor',
'Manuscript format',
'Medical writing',
'Novelist',
'Poet',
'Polygraph (author)',
'Review',
'Screenwriter',
'Scribe',
'Script coordinator',
'Script doctor',
'Scrivener',
'Songwriter',
'Speechwriter',
'Staff writer',
'Technical writer',
'Website content writer',
'Veterinarian',
'Biologist',
'Biomedical scientist',
'Botanist',
'Herpetologist',
'Medical laboratory scientist',
'Microbiologist',
'Neuroscientist',
'Clinical pharmaceutical scientist',
'Zoologist',
'Physician',
'Aeronautical engineer',
'Biomedical engineer',
'Civil engineer',
'Chemical engineer',
'Educational technologist',
'Electrical engineer',
'Engineering technician',
'Engineering technologist',
'Petrochemical engineer',
'Mechanical engineer',
'Forensic scientist',
'Gentleman scientist',
'Government scientist',
'Healthcare science',
'Hiwi',
'Inventor',
'Psychologist',
'Research fellow',
'School science technician',
'Science attaché',
'Scientist',
'Archaeologist',
'Astronaut',
'Astronomer',
'Biochemist',
'Biologist',
'Chemist',
'Ecologist[8]',
'Forester',
'Geographer',
'Naturalist',
'Oceanographer',
'Paleontologist',
'Pathologist',
'Geographer',
'Geologist',
'Geoprofessions',
'Petroleum geologist',
'Anthropologist',
'Economist',
'Historian',
'Political scientist',
'Sociologist',
'Urban planner',
]

module.exports = [
    works
]